name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Пушим содержимое этого репо прямо в репозиторий Space
      - name: Push to Hugging Face Space (git remote)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}         # секрет в GitHub: Settings → Secrets → Actions
          HF_SPACE: "HomeOrganization/Comparison"   # путь к вашему Space
        run: |
          set -e
          git remote add hf "https://oauth2:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git" \
            || git remote set-url hf "https://oauth2:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git"
          git fetch hf || true
          git checkout -B main
          git push -f hf main:main
